#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2026 FreeFlow Networks, Inc.
"""Make Buildroot build the OpenSSL 3.x FIPS provider for FFN's OCTEON planes.

Buildroot 2025.02.9 offers no FIPS knob at all -- package/libopenssl carries
zero mentions of fips -- so enable-fips has to be added to OpenSSL's Configure
invocation by hand.

The obvious-looking seam is a trap. BR2_PACKAGE_LIBOPENSSL_TARGET_ARCH is
splatted verbatim into the Configure line, so setting it to
"linux-generic64 no-asm enable-fips" appears to work, and it does build fips.so
once. But that symbol is a computed Kconfig string with no prompt: the next
syncconfig regenerates it from its arch default and the setting evaporates,
leaving a tree that quietly stops producing a FIPS provider. The same applies
to putting it in a defconfig. This caught us once already.

local.mk is not an option either -- 2025.02.9's Makefile has no local.mk hook
at all -- and BR2_EXTERNAL is included at line 192, before package/*/*.mk at
535, so a package override there loses to the package's own definition.

That leaves editing the package makefile, done here as a script so the change
is reproducible and reviewable rather than a hand-edit nobody can find later.

enable-fips is unconditional: FFN wants a FIPS-capable userland on every plane,
so there is no configuration in which we would want it off, and a new Kconfig
symbol would be ceremony around a constant.

Matching is done line-wise on 'enable-camellia' with no backslash literals
anywhere: the continuation backslashes in that makefile block do not survive
being typed through several layers of shell quoting, which already produced one
silently non-matching version of this script.

Idempotent: re-running detects the marker and does nothing.
"""
import sys

MK = "/root/buildroot-2025.02.9/package/libopenssl/libopenssl.mk"
MARKER = "FFN: enable-fips"
BS = chr(92)                      # a literal backslash, kept out of the source

NOTE = [
    "# FFN: enable-fips -- build the OpenSSL 3.x FIPS provider (providers/fips.so).",
    "# Added unconditionally; Buildroot 2025.02.9 has no FIPS option of its own and",
    "# the BR2_PACKAGE_LIBOPENSSL_TARGET_ARCH string is regenerated by syncconfig,",
    "# so this is the only place the option survives. Note that `make install` does",
    "# NOT run OpenSSL's install_fips target (which would try to execute the mips64",
    "# openssl binary on the x86 build host); install_modules places fips.so, and",
    "# /etc/ssl/fipsmodule.cnf is generated on the target by /sbin/ffn-fips.sh.",
]

DEFINE = "define LIBOPENSSL_CONFIGURE_CMDS"


def main():
    src = open(MK).read()
    if MARKER in src:
        print("already patched")
        return 0

    lines = src.split("\n")

    # locate the TARGET configure block; the HOST openssl is a build tool and
    # has no business carrying a FIPS module, so only this one is touched
    try:
        start = lines.index(DEFINE)
    except ValueError:
        sys.stderr.write("define %s not found -- Buildroot version changed?\n" % DEFINE)
        return 1

    end = start
    while end < len(lines) and lines[end] != "endef":
        end += 1

    hit = None
    for i in range(start, end):
        if lines[i].strip().startswith("enable-camellia"):
            hit = i
            break
    if hit is None:
        sys.stderr.write("no enable-camellia line inside the target block\n")
        return 1

    # mirror the indentation of the line we are following so the block stays
    # readable, and reuse its trailing continuation
    indent = lines[hit][:len(lines[hit]) - len(lines[hit].lstrip())]
    lines.insert(hit + 1, indent + "enable-fips " + BS)
    lines[start:start] = NOTE

    open(MK, "w").write("\n".join(lines))
    print("patched %s (enable-fips after line %d)" % (MK, hit + 1))
    return 0


if __name__ == "__main__":
    sys.exit(main())
