#!/bin/bash
# Stage FFN's OCTEON boot artifacts into /var/lib/tftpboot.
#
# This is FFN's equivalent of what PAN-OS does from masterd: grp_control_plane's
# vmlinux_copy() drops vmlinux.mp / vmlinux.oct2-mp into /var/lib/tftpboot as
# vmlinux.cp, and grp_chassis adds pxelinux.0, a pxelinux config and a dhcpd
# config so a plane can netboot.
#
# WHAT THIS IS AND IS NOT USED FOR, so nobody wires it up expecting magic:
#
#   * On a PA-5220 nothing netboots today. The CP is loaded over PCIe
#     (oct-remote-boot into L2 cache, then a mailbox bootcmd), and the DP is not
#     reachable at all yet. So this staging is inert on this chassis.
#   * It matters in two futures: 7000-series line cards, which genuinely PXE
#     boot over the chassis Ethernet; and the DP on this box once the BCM switch
#     bridges the X552 backplane, at which point netbooting a plane becomes the
#     simplest option and needs no PCIe staging at all.
#   * TFTP is also a convenient way to hand a plane a kernel without the ~3.5
#     minute SLI staging step, which is worth having during bring-up.
#
# Everything staged here is FFN's own build. No vendor images are copied in --
# the vendor kernel stays where it is and is used in place when needed.
set -euo pipefail

TFTP=${TFTP:-/var/lib/tftpboot}
OCT=${OCT:-/var/lib/ffn-ngfw/octeon}
KERNEL=${KERNEL:-$OCT/ffn-vmlinux-octeon3}
ROOTFS_SQUASH=${ROOTFS_SQUASH:-$OCT/ffn-dprootfs.squashfs}
ROOTFS_CPIO=${ROOTFS_CPIO:-$OCT/ffn-dprootfs.cpio}
NFSROOT=${NFSROOT:-/opt/dpfs}
SRV=${SRV:-127.1.1.1}

say() { printf '  %s\n' "$*"; }

[ -f "$KERNEL" ] || { echo "no kernel at $KERNEL"; exit 1; }

mkdir -p "$TFTP" "$TFTP/pxelinux.cfg"

# vmlinux.cp is the name PAN-OS's vmlinux_copy() uses, kept so a plane or line
# card configured against the vendor layout finds FFN's kernel where it looks.
install -m644 "$KERNEL" "$TFTP/vmlinux.cp"
say "vmlinux.cp            $(stat -c %s "$TFTP/vmlinux.cp") bytes"

# Keep the descriptive name alongside it; the symlink costs nothing and makes
# the directory self-explaining when someone lists it in two years.
ln -sf vmlinux.cp "$TFTP/ffn-vmlinux-octeon3"

for f in "$ROOTFS_SQUASH" "$ROOTFS_CPIO"; do
    [ -f "$f" ] || continue
    install -m644 "$f" "$TFTP/$(basename "$f")"
    say "$(basename "$f")  $(stat -c %s "$f") bytes"
done

# pxelinux.0 only exists if syslinux is installed; its absence is not fatal
# because the Octeon path does not use it -- it is for line cards.
for p in /usr/lib/syslinux/pxelinux.0 /usr/lib/PXELINUX/pxelinux.0 \
         /usr/lib/syslinux/modules/bios/pxelinux.0; do
    [ -f "$p" ] || continue
    install -m644 "$p" "$TFTP/pxelinux.0"
    say "pxelinux.0            staged from $p"
    break
done
[ -f "$TFTP/pxelinux.0" ] || say "pxelinux.0            absent (syslinux not installed; not needed for OCTEON)"

# The boot line mirrors what FFN uses over PCIe today, minus the staging: mem=
# carries a SUFFIX because arch/mips/cavium-octeon/setup.c parses it with
# memparse(), so a bare "mem=2048" would mean 2048 BYTES. numcores=8 is the CP;
# a DP would want 40 on a PA-5220.
cat > "$TFTP/pxelinux.cfg/default" <<EOF
# FFN NGFW -- OCTEON plane netboot
# Generated by octeon/rootfs/build_tftpboot.sh; edit that, not this.
DEFAULT ffn-cp
PROMPT 0
TIMEOUT 30

LABEL ffn-cp
    KERNEL vmlinux.cp
    APPEND numcores=8 console=ttyS0,115200n8 mem=2G rw \\
           root=/dev/nfs nfsroot=$SRV:$NFSROOT,v3 \\
           ip=127.1.1.2:$SRV:$SRV:255.255.255.0:octeon:pci0

LABEL ffn-cp-initramfs
    KERNEL vmlinux.cp
    APPEND numcores=8 console=ttyS0,115200n8 mem=2G rw
EOF
say "pxelinux.cfg/default  written (nfsroot=$SRV:$NFSROOT,v3)"

cat > "$TFTP/README" <<'EOF'
FFN OCTEON netboot staging
==========================
vmlinux.cp                FFN's OCTEON kernel, under the name PAN-OS uses
ffn-vmlinux-octeon3       symlink to the same file
ffn-dprootfs.squashfs     full MIPS64 BE rootfs, read-only (pair with overlayfs)
ffn-dprootfs.cpio         same tree as a raw newc cpio
pxelinux.cfg/default      boot entries: NFS root, or plain initramfs

Nothing on a PA-5220 netboots today: the CP is loaded over PCIe and the DP is
not reachable. This exists for 7000-series line cards, and for this box's DP
once the BCM switch bridges the X552 backplane.

The NFS entry expects the MP's export to be reachable, which on this design
means over PCIC only -- see /etc/nfs.conf.d/10-ffn-pcic.conf. The 127.1.x.x
addressing is deliberate: 127/8 is non-routable, so the export cannot be
reached from any physical topology even if a port were left open.
EOF
say "README                written"

echo
say "staged into $TFTP:"
ls -la "$TFTP" | tail -n +2 | sed 's/^/    /'
