#!/bin/sh
# ffn-fips.sh -- activate the OpenSSL 3.x FIPS provider on an FFN plane.
#
# Runs on the target (CP or DP), not the build host, and that is the whole
# reason this file exists.
#
# The FIPS provider needs /etc/ssl/fipsmodule.cnf, which carries an HMAC-SHA256
# integrity MAC over fips.so plus the recorded result of the module's power-on
# self-tests. That file is produced by `openssl fipsinstall`, which does not
# merely hash the file -- it LOADS the module and asks it to self-test. So it
# has to execute mips64 big-endian code, and an x86 build host cannot do it.
# Buildroot's cross build therefore ships fips.so with no fipsmodule.cnf, and
# generating it here at boot is not a workaround: a power-on self test is what
# FIPS 140-3 asks for anyway.
#
# The rootfs is an initramfs (tmpfs), so /etc/ssl is writable and the generated
# file simply lives for the life of the boot. Nothing needs to persist.
#
# Writing fipsmodule.cnf is NOT sufficient on its own. The provider reads its
# config through openssl.cnf, and without an `.include` of fipsmodule.cnf any
# attempt to load it dies with
#
#     SELF_TEST_post: missing config data ... fips module entering error state
#
# which reads like a failed self-test and is really a missing include. So the
# config is always rewritten here, and the provider is always made loadable.
#
# ENFORCEMENT is separate and opt-in. Making the module available is one
# decision; restricting every consumer on the box to approved algorithms is a
# different and much louder one, and switching it on unannounced mid-bring-up
# would change SSH and TLS behaviour underneath work still in progress. Without
# ffn_fips=1 the fips, base and default providers are all active, so anything
# that asks for fips=yes gets FIPS and everything else keeps working. With
# ffn_fips=1 the default provider is dropped and fips=yes becomes the default
# property, so non-approved algorithms stop resolving everywhere.
#
# Exit status is deliberately 0 even when FIPS is unavailable: this is called
# from init, and a non-zero exit there has already cost this board its shell
# once. Report loudly, never block the boot.

PROVIDER_DIR=/usr/lib/ossl-modules
FIPS_SO=$PROVIDER_DIR/fips.so
SSLDIR=/etc/ssl
FIPS_CNF=$SSLDIR/fipsmodule.cnf
CNF=$SSLDIR/openssl.cnf
OPENSSL=/usr/bin/openssl

say() { echo "FFN-FIPS: $*"; }

[ -x "$OPENSSL" ] || { say "no openssl binary at $OPENSSL; nothing to do"; exit 0; }

if [ ! -f "$FIPS_SO" ]; then
	say "no FIPS provider at $FIPS_SO"
	say "the userland was built without enable-fips; FIPS mode is unavailable"
	exit 0
fi

# Generate the module config. -self_test_onload records that the self-tests are
# to run each time the module loads rather than trusting a stored result, which
# is the right posture for a box that regenerates this file every boot anyway.
if [ ! -f "$FIPS_CNF" ]; then
	say "running fipsinstall -- self-test + integrity MAC over fips.so"
	if ! $OPENSSL fipsinstall -out "$FIPS_CNF" -module "$FIPS_SO" \
	     -self_test_onload >/tmp/ffn-fipsinstall.log 2>&1; then
		say "fipsinstall FAILED -- FIPS unavailable; see /tmp/ffn-fipsinstall.log"
		sed 's/^/FFN-FIPS:   /' /tmp/ffn-fipsinstall.log 2>/dev/null | head -12
		rm -f "$FIPS_CNF"
		exit 0
	fi
	say "fipsinstall OK -- $FIPS_CNF written"
fi

mac=$(sed -n 's/^module-mac *= *//p' "$FIPS_CNF" 2>/dev/null | head -1)
say "module MAC ${mac:-<none>}"

if grep -q "ffn_fips=1" /proc/cmdline 2>/dev/null; then
	enforce=1
else
	enforce=0
fi

[ -f "$CNF" ] && [ ! -f "$CNF.pre-ffn-fips" ] && cp "$CNF" "$CNF.pre-ffn-fips"

# base is listed alongside fips in both modes on purpose: the fips provider
# deliberately does not implement the non-cryptographic pieces (encoders, PEM
# handling), and leaving base out breaks key loading in ways that surface as
# unrelated-looking TLS errors.
{
	echo "# Generated by ffn-fips.sh. Do not edit -- rewritten every boot."
	echo "config_diagnostics = 1"
	echo "openssl_conf = openssl_init"
	echo ""
	echo ".include $FIPS_CNF"
	echo ""
	echo "[openssl_init]"
	echo "providers = provider_sect"
	[ "$enforce" = 1 ] && echo "alg_section = algorithm_sect"
	echo ""
	echo "[provider_sect]"
	echo "fips = fips_sect"
	echo "base = base_sect"
	[ "$enforce" = 0 ] && echo "default = default_sect"
	echo ""
	echo "[base_sect]"
	echo "activate = 1"
	if [ "$enforce" = 0 ]; then
		echo ""
		echo "[default_sect]"
		echo "activate = 1"
	else
		echo ""
		echo "[algorithm_sect]"
		echo "default_properties = fips=yes"
	fi
} > "$CNF"

if $OPENSSL list -providers 2>/dev/null | grep -q "^ *fips"; then
	if [ "$enforce" = 1 ]; then
		say "FIPS mode ENFORCED -- approved algorithms only"
	else
		say "FIPS provider active and loadable; not enforced"
		say "anything requesting fips=yes gets FIPS; boot with ffn_fips=1 to enforce"
	fi
else
	say "WARNING: the fips provider did not load"
	$OPENSSL list -providers 2>&1 | sed 's/^/FFN-FIPS:   /' | head -12
	say "restoring the previous openssl.cnf so TLS keeps working"
	[ -f "$CNF.pre-ffn-fips" ] && cp "$CNF.pre-ffn-fips" "$CNF"
fi
exit 0
