#!/usr/bin/env python3
"""FE100 DIRECT next-hop adapter for the hash-pinned local owner library.

Default inspects one slot. --roundtrip commissions an empty slot and removes
it in finally. No table flush, LIF change, or lookup-engine initialization.
Caller must set the same LD_LIBRARY_PATH as ffn-fe100-links.sh.
"""
import argparse
import ctypes as C
import fcntl
import hashlib
import json
import os
import struct
import subprocess
import sys
from ffn_fe100 import bar0_base_and_size, memory_decode_on

LIB = '/opt/ffn-compat/tmp/dpfs/usr/local/lib64/libpandp_cp.so.1.0'
SHA = 'b57227a460144c8c2545fc2e268b31f475ef72ac2a6f1d457387ab46d842c3e9'


def encode(destination=8, dmac=None, vlan=None, mtu=1518):
    if type(destination) is not int or not 0 <= destination < 16:
        raise ValueError('system port must be 0..15')
    if type(mtu) is not int or not 64 <= mtu <= 9216:
        raise ValueError('invalid MTU')
    if vlan is not None and (type(vlan) is not int or not 1 <= vlan <= 4094):
        raise ValueError('invalid VLAN')
    mac = bytes.fromhex(dmac.replace(':', '')) if dmac else bytes(6)
    if len(mac) != 6 or (dmac and (mac[0] & 1 or not any(mac))):
        raise ValueError('destination MAC must be unicast and nonzero')
    # Owner DWARF: 16-byte BE structure; valid bit23, do_sysport bit20,
    # do_vlan bit18, do_da bit16. Egress LIF at4, VID6, MTU8, dmac10.
    flags = (1 << 23) | (1 << 20) | ((vlan is not None) << 18) | (bool(dmac) << 16)
    return struct.pack('>IHHH6s', flags, destination, vlan or 0, mtu, mac)


class NextHop:
    def __init__(self):
        self.lock = open('/run/ffn-fe100-tables.lock', 'w')
        fcntl.flock(self.lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
        with open(LIB, 'rb') as f:
            if hashlib.file_digest(f, 'sha256').hexdigest() != SHA:
                raise RuntimeError('owner ABI changed')
        base, size = bar0_base_and_size()
        if size != 0x100000 or not memory_decode_on():
            raise RuntimeError('FE100 unavailable')
        self.shim = C.CDLL('/usr/local/lib/ffn/libffn-fe100-tables.so', mode=os.RTLD_GLOBAL | os.RTLD_NOW)
        self.lib = C.CDLL(LIB, mode=os.RTLD_LOCAL | os.RTLD_LAZY)
        cmd = self.lib.fe100_ia_cmd_addr
        cmd.argtypes = [C.c_uint32]
        cmd.restype = C.c_uint32
        if cmd(10) != 0x50300 or self.shim.ffn_fe100_select_block(0x50000):
            raise RuntimeError('DIRECT next-hop IA block changed')
        self.shim.ffn_fe100_open.argtypes = [C.c_uint64, C.c_char_p, C.c_int]
        if self.shim.ffn_fe100_open(base, b'/var/lib/ffn/fe100/nexthop-trace.txt', 1):
            raise RuntimeError('map failed')
        for r in json.load(open('/opt/ffn-compat/opt/ffn/fe100-csr.json')):
            self.shim.ffn_fe100_allow(r['addr'])
        for name in ('fetch', 'insert'):
            fn = getattr(self.lib, 'pan_fe100_'+name+'_nexthop_entry')
            fn.argtypes = [C.c_uint32, C.c_void_p, C.c_int, C.c_int]
            fn.restype = C.c_int
        self.lib.pan_fe100_delete_nexthop_entry.argtypes = [C.c_uint32, C.c_int, C.c_int]
        self.lib.pan_fe100_delete_nexthop_entry.restype = C.c_int

    def fetch(self, index):
        entry = (C.c_ubyte * 16)()
        rc = self.lib.pan_fe100_fetch_nexthop_entry(0, entry, 0, index)
        if rc not in (0, 3):
            raise RuntimeError('next-hop fetch returned '+str(rc))
        return rc, bytes(entry)

    def put(self, index, entry):
        rc = self.lib.pan_fe100_insert_nexthop_entry(0, (C.c_ubyte * 16).from_buffer_copy(entry), 0, index)
        if rc:
            raise RuntimeError('next-hop insert returned '+str(rc))

    def delete(self, index):
        rc = self.lib.pan_fe100_delete_nexthop_entry(0, 0, index)
        if rc:
            raise RuntimeError('next-hop delete returned '+str(rc))


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--index', type=int, default=31)
    p.add_argument('--roundtrip', action='store_true')
    p.add_argument('--direct-lif-test', action='store_true')
    args = p.parse_args()
    if not 0 <= args.index < 32:
        p.error('commissioning slots are limited to 0..31')
    nh = NextHop()
    rc, before = nh.fetch(args.index)
    print(json.dumps({'index': args.index, 'fetch_rc': rc, 'entry': before.hex()}), flush=True)
    if not (args.roundtrip or args.direct_lif_test):
        return
    if args.direct_lif_test and args.index != 31:
        raise RuntimeError('DIRECT LIF commissioning requires next-hop31')
    if rc != 3 or before[1] & 0x80:
        raise RuntimeError('refusing to replace a valid next-hop')
    wanted = encode(dmac='02:52:20:ab:cd:ee', vlan=None if args.direct_lif_test else 123)
    try:
        nh.put(args.index, wanted)
        rc, actual = nh.fetch(args.index)
        # ECC byte is generated by hardware and is not payload.
        if rc or actual[1:] != wanted[1:]:
            raise RuntimeError('next-hop payload did not read back')
        print(json.dumps({'test': 'fe100-direct-nexthop-write-read', 'entry': actual.hex(), 'passed': True}), flush=True)
        if args.direct_lif_test:
            subprocess.run([sys.executable, os.path.join(os.path.dirname(__file__), 'ffn_fe100_direct_lif_test.py')],
                           env={**os.environ, 'FFN_FE100_LOCK_FD': str(nh.lock.fileno())},
                           pass_fds=(nh.lock.fileno(),), check=True)
    finally:
        nh.delete(args.index)
        rc, actual = nh.fetch(args.index)
        if rc != 3 or actual[1] & 0x80:
            raise RuntimeError('next-hop cleanup failed')
        print(json.dumps({'test': 'fe100-direct-nexthop-empty-restored', 'passed': True}), flush=True)


if __name__ == '__main__':
    main()
